include $(TOPDIR)/config.mk

LIB	:= $(obj)libsecurity.o

COBJS-$(CONFIG_SECURITY) += scm.o

COBJS	:= $(sort $(COBJS-y))
SRCS	:= $(COBJS:.o=.c)
OBJS	:= $(addprefix $(obj),$(COBJS))
CFLAGS += -mcpu=cortex-a9
all:	$(LIB)

$(LIB):	$(obj).depend $(OBJS)
	$(call cmd_link_o_target, $(OBJS))

#########################################################################

# defines $(obj).depend target
include $(SRCTREE)/rules.mk

sinclude $(obj).depend

#########################################################################
